train:
  random_state: 42
  test_size: 0.2
  n_estimators: 120
  min_samples_leaf: 2
  n_clusters: 4
  dbscan_eps: 0.95
  dbscan_min_samples: 12
  run_maps: true
  optuna_trials: 0

data:
  source_csv: data/Global YouTube Statistics.csv
  processed_csv: data/global_youtube_statistics_processed.csv
